Add blog post draft for the 0.3 release announcement.
QMSTR/web pull request #37
Opened 2019-02-05 10:55 UTC by mirkoboehm

Comments welcome.

2019-02-05 12:40 UTC, GiasemiSh approved these changes
lgtm

2019-02-05 13:22 UTC, thegrumpylion requested changes

2019-02-05 13:22 UTC, thegrumpylion commented on content/blog/qmstr-milestone-3-report.md
> +analysing source code elements that are generated during the build and
analysing -> analyzing

2019-02-05 13:22 UTC, thegrumpylion commented on content/blog/qmstr-milestone-3-report.md
> +of the knowledge graph, which allows to roll back changes to a known
to roll -> rolling

2019-02-05 13:22 UTC, thegrumpylion commented on content/blog/qmstr-milestone-3-report.md
> +results. Support for the C++ programing language was extended through
programing -> programming

2019-02-05 13:22 UTC, thegrumpylion commented on content/blog/qmstr-milestone-3-report.md
> +umbrella organisation form the start. With the upcoming launch of
form -> from

2019-02-05 13:36 UTC, hemarkus requested changes
minor changes required

2019-02-05 13:36 UTC, hemarkus commented on content/blog/qmstr-milestone-3-report.md
> +binary. The code is now saved in the knowledge graph for inspection.
It is actually not saved in the graph but in the file system to get checked by e.g. scancode

2019-02-05 13:36 UTC, hemarkus commented on content/blog/qmstr-milestone-3-report.md
> +feature of the underlying DGraph database. This effort will continue
it is not a feature of dgraph but more a best practice to model your structs

2019-02-06 16:14 UTC, Katajau reviewed
Looks great, just one small typo.

2019-02-06 16:14 UTC, Katajau commented on content/blog/qmstr-milestone-3-report.md
> +umbrella organisation form the start. With the upcoming launch of
umbrella organisation from (or is form correct?) the start.

2019-02-07 10:35 UTC, mirkoboehm commented on content/blog/qmstr-milestone-3-report.md
> +umbrella organisation form the start. With the upcoming launch of
Fixed.

2019-02-07 11:06 UTC, merged